apiVersion: v1
kind: ConfigMap
metadata:
  name: startup
  labels:
    {{- include "ejabberd.labels" . | nindent 4 }}
data:
  cluster.sh: |-
    {{- if .Values.startupScript }}
      {{- printf "%s" (tpl .Values.startupScript $) | nindent 4 }}
    {{- else }}
      {{- tpl (.Files.Get "files/cluster.sh") . | nindent 4 }}
    {{- end }}
